# SPDX-License-Identifier: BSD-2-Clause
# Symbols with information about the CPU.

IF(CMAKE_SYSTEM_NAME MATCHES "Darwin")
  FIND_PROGRAM(SYSCTL sysctl)
  MARK_AS_ADVANCED(SYSCTL)

  IF(SYSCTL)
    EXECUTE_PROCESS(
      COMMAND ${SYSCTL} -n hw.cachelinesize
      OUTPUT_VARIABLE CPU_LEVEL1_DCACHE_LINESIZE
      )
  ENDIF()

ELSE()
  FIND_PROGRAM(GETCONF getconf)
  MARK_AS_ADVANCED(GETCONF)

  IF(GETCONF)
    EXECUTE_PROCESS(
      COMMAND ${GETCONF} LEVEL1_DCACHE_LINESIZE
      OUTPUT_VARIABLE CPU_LEVEL1_DCACHE_LINESIZE
      )
  ENDIF()
ENDIF()
